name: Common Steps
description: Common steps for GitHub Actions
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.9'
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Ensure docker-compose is available
      run: docker-compose version
      shell: bash

    - name: Ensure make is available
      run: make --version
      shell: bash
