name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Common Steps
        uses: ./.github/actions/common-steps

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Common Steps
        uses: ./.github/actions/common-steps

      - name: Run tests with Makefile
        run: make test

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Common Steps
        uses: ./.github/actions/common-steps

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
